# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a904f0bbc3d4abd8a9fa88cd4e2d3adbd80732951e8228005ccffb08979db32034bba8814a1c7bb0ee345c4452c0d3dfd57e4d90a43a78d0e5af9f515c951df4

test:
  secret_key_base: 88724f8c682095cb3c3d1e93a9ecf5611083e187a76984b11997f7c46824a4b98f85473470f4ad363e6353f5142c90824ee8ae2703c3fc25bb3fc63b6bc19731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
